# docker-compose.yml
version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: patrick-salvatore
      POSTGRES_PASSWORD: secret-password
      POSTGRES_DB: workout-room
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  backend:
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    command: npm run start
 

