export interface DateTimePickerProps {
  children?: React.ReactNode;
  dateFormat?: string;
  dateFormatCalendar?: string;
  disabled?: boolean;
  dropdownMode: 'scroll' | 'select';
  endDate?: Date;
  excludeDates?: Date[];
  includeDates?: Date[];
  inline?: boolean;
  locale?: string;
  maxDate?: Date;
  maxTime?: Date;
  minDate?: Date;
  minTime?: Date;
  monthsShown?: number;
  className?: string;
  onChange?: (date: Date, event: React.ChangeEvent<HTMLInputElement>) => void;
  selected?: Date;
  selectsEnd?: boolean;
  selectsStart?: boolean;
  showMonthDropdown?: boolean;
  showTimeSelect?: boolean;
  showYearDropdown?: boolean;
  showTimeSelectOnly?: boolean;
  startDate?: Date;
  timeFormat?: string;
  timeIntervals?: number;
  timeCaption?: string;
  todayButton?: string;
  withPortal?: boolean;
  isValid?: boolean;
  isInvalid?: boolean;
  feedback?: string;
  error?: boolean;
  label?: string;
}
